#!/usr/bin/env python3
"""
mlstdb_to_ariba.py

Convert mlstdb update output to ariba pubmlstget-compatible format.

mlstdb output layout:
  <mlstdb_dir>/
    pubmlst/<scheme>/
      arcC.tfa          (headers: >arcC_1)
      <scheme>.txt      (profile, same TSV format as ariba)
      <scheme>_info.json

ariba pubmlstget output layout:
  <outdir>/
    clusters.tsv         (one line per gene, tab-separated allele names gene.N)
    pubmlst_download/
      arcC.tfa           (headers: >arcC.1)
      profile.txt
    ref_db/              (generated by ariba prepareref)
      pubmlst.profile.txt
      ...

Usage examples:
  python mlstdb_to_ariba.py -i mlstdb_saureus -o s_aureus_ariba
  python mlstdb_to_ariba.py -i mlstdb_saureus -s saureus -o s_aureus_ariba --no-prepareref
"""

import argparse
import json
import logging
import os
import shutil
import statistics
import subprocess
import sys
from datetime import datetime
from pathlib import Path


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

def _setup_logging():
    logging.basicConfig(
        format="[%(levelname)s] [%(asctime)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
        level=logging.INFO,
        stream=sys.stderr,
    )

log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# FASTA helpers (no external deps)
# ---------------------------------------------------------------------------

def read_fasta(path):
    """Parse a FASTA file {header: sequence} keeping insertion order."""
    sequences = {}
    current_name = None
    current_seq = []
    with open(path) as fh:
        for line in fh:
            line = line.rstrip("\n")
            if line.startswith(">"):
                if current_name is not None:
                    sequences[current_name] = "".join(current_seq)
                current_name = line[1:]
                current_seq = []
            else:
                current_seq.append(line)
        if current_name is not None:
            sequences[current_name] = "".join(current_seq)
    return sequences


def write_fasta(path, sequences):
    """Write {header: sequence} to a FASTA file, 60-char wrapped."""
    with open(path, "w") as fh:
        for name, seq in sequences.items():
            fh.write(f">{name}\n")
            for i in range(0, len(seq), 60):
                fh.write(seq[i:i+60] + "\n")


def filter_by_length(sequences, gene_name):
    """
    Remove alleles whose length is outside 90–110 % of the median.
    Mirrors ariba's PubmlstRefPreparer._filter_seq_dict().
    Returns a new dict; warns about removed sequences.
    """
    if not sequences:
        return sequences

    lengths = sorted(len(s) for s in sequences.values())
    median = statistics.median(lengths)
    lo, hi = 0.9 * median, 1.1 * median

    filtered = {}
    for name, seq in sequences.items():
        if lo <= len(seq) <= hi:
            filtered[name] = seq
        else:
            log.warning(
                "Median length for %s is %d; %s has length %d — removed (outside 90–110%%).",
                gene_name, int(median), name, len(seq),
            )
    return filtered


# ---------------------------------------------------------------------------
# Auto-detection of scheme directory
# ---------------------------------------------------------------------------

def detect_scheme(mlstdb_dir):
    """
    mlstdb places files in <mlstdb_dir>/pubmlst/<scheme>/.
    Returns (scheme_name, scheme_dir) for the first scheme found.
    """
    pubmlst_root = Path(mlstdb_dir) / "pubmlst"
    if not pubmlst_root.is_dir():
        raise FileNotFoundError(
            f"No 'pubmlst/' subdirectory found in {mlstdb_dir}."
            "Is this a valid mlstdb output directory?"
        )

    schemes = [d for d in pubmlst_root.iterdir() if d.is_dir()]
    if not schemes:
        raise FileNotFoundError(f"No scheme subdirectories found under {pubmlst_root}.")
    if len(schemes) > 1:
        names = [d.name for d in schemes]
        raise ValueError(
            f"Multiple schemes found: {names}."
            "Use --scheme to specify which one to convert."
        )
    return schemes[0].name, schemes[0]


# ---------------------------------------------------------------------------
# Core conversion
# ---------------------------------------------------------------------------

def convert(mlstdb_dir, outdir, scheme=None, ariba_bin="ariba", run_prepareref=True):
    mlstdb_dir = Path(mlstdb_dir).resolve()
    outdir = Path(outdir).resolve()

    # -- locate scheme directory ------------------------------------------
    if scheme:
        scheme_dir = mlstdb_dir / "pubmlst" / scheme
        if not scheme_dir.is_dir():
            raise FileNotFoundError(f"Scheme directory not found: {scheme_dir}")
    else:
        scheme, scheme_dir = detect_scheme(mlstdb_dir)
        log.info("Auto-detected scheme: %s", scheme)

    log.info("Using mlstdb scheme directory: %s", scheme_dir)

    # -- read info JSON -------------------------------------------------------
    info_json = scheme_dir / f"{scheme}_info.json"
    if info_json.exists():
        with open(info_json) as fh:
            info = json.load(fh)
        log.info(
            "Scheme: %s | source: %s | downloaded: %s | last updated: %s",
            info.get("name"), info.get("source"), info.get("download_date"),
            info.get("last_updated"),
        )

    # -- read profile to get gene order ---------------------------------------
    profile_src = scheme_dir / f"{scheme}.txt"
    if not profile_src.exists():
        raise FileNotFoundError(f"Profile file not found: {profile_src}")

    with open(profile_src) as fh:
        header = fh.readline().rstrip("\n").split("\t")

    if header[0].upper() != "ST":
        raise ValueError(f"Unexpected profile header (expected 'ST' first): {header}")

    # Filter profile columns to only those with a corresponding .tfa file.
    # Some schemes include metadata columns (e.g. clonal_complex, species)
    # that are not sequence loci and have no .tfa file.
    all_columns = header[1:]
    genes = [col for col in all_columns if (scheme_dir / f"{col}.tfa").exists()]
    skipped = [col for col in all_columns if col not in genes]
    if skipped:
        log.info(
            "Skipping %d non-locus profile column(s) (no .tfa file): %s",
            len(skipped), ", ".join(skipped),
        )
    log.info("Genes in scheme (%d): %s", len(genes), ", ".join(genes))

    # -- prepare output directories ------------------------------------------
    if outdir.exists():
        raise FileExistsError(
            f"Output directory already exists: {outdir}\n"
            "Remove it first or choose a different name."
        )
    download_dir = outdir / "pubmlst_download"
    download_dir.mkdir(parents=True)

    # -- process each gene ----------------------------------------------------
    fasta_paths = []
    clusters_rows = []

    for gene in genes:
        tfa_src = scheme_dir / f"{gene}.tfa"
        if not tfa_src.exists():
            raise FileNotFoundError(
                f"Allele FASTA not found for gene '{gene}': {tfa_src}"
            )

        raw = read_fasta(tfa_src)
        log.info("Gene %-8s: %d alleles read", gene, len(raw))

        # Convert headers: gene_N  -->  gene.N
        converted = {}
        for old_name, seq in raw.items():
            # Handle both "gene_N" and "gene.N" (in case already converted)
            if "_" in old_name:
                parts = old_name.rsplit("_", 1)
                new_name = f"{parts[0]}.{parts[1]}"
            elif "." in old_name:
                new_name = old_name  # already in ariba format
            else:
                new_name = old_name
            converted[new_name] = seq

        # Apply length filter (mirrors ariba behaviour)
        filtered = filter_by_length(converted, gene)
        if len(filtered) < len(converted):
            log.info(
                "Gene %-8s: %d alleles retained after length filtering (removed %d).",
                gene, len(filtered), len(converted) - len(filtered),
            )

        # Write converted FASTA (sorted by allele name for reproducibility)
        sorted_seqs = dict(sorted(filtered.items(), key=lambda kv: _allele_sort_key(kv[0])))
        tfa_dst = download_dir / f"{gene}.tfa"
        write_fasta(tfa_dst, sorted_seqs)
        fasta_paths.append(tfa_dst)

        # Clusters line: all allele names tab-separated
        allele_names = list(sorted_seqs.keys())
        clusters_rows.append(allele_names)

    # -- write clusters.tsv --------------------------------------------------
    clusters_file = outdir / "clusters.tsv"
    with open(clusters_file, "w") as fh:
        for row in clusters_rows:
            fh.write("\t".join(row) + "\n")
    log.info("Wrote clusters.tsv (%d genes).", len(clusters_rows))

    # -- copy profile --------------------------------------------------------
    profile_dst = download_dir / "profile.txt"
    shutil.copy(profile_src, profile_dst)
    log.info("Copied profile: pubmlst_download/profile.txt")

    # -- run ariba prepareref ------------------------------------------------
    if run_prepareref:
        ref_db_dir = outdir / "ref_db"
        cmd = [ariba_bin, "prepareref"]
        for fp in fasta_paths:
            cmd += ["-f", str(fp)]
        cmd += [
            "--cdhit_clusters", str(clusters_file),
            "--all_coding", "no",
            str(ref_db_dir),
        ]
        log.info("Running: %s", " ".join(cmd))
        result = subprocess.run(cmd, capture_output=False)
        if result.returncode != 0:
            raise RuntimeError(
                f"ariba prepareref failed with exit code {result.returncode}."
                "Check output above for details."
            )

        # Copy profile into ref_db/ (ariba looks for it there during 'run')
        shutil.copy(profile_src, ref_db_dir / "pubmlst.profile.txt")
        log.info("Copied profile: ref_db/pubmlst.profile.txt")
        log.info("Done. Use the database with:")
        log.info("  ariba run %s reads_1.fq reads_2.fq output_dir", ref_db_dir)
    else:
        log.info(
            "Skipped ariba prepareref (--no-prepareref). "
            "Run manually:\n  ariba prepareref %s --cdhit_clusters %s "
            "--all_coding no <ref_db_outdir>",
            " ".join(f"-f {p}" for p in fasta_paths),
            clusters_file,
        )

    return outdir


def _allele_sort_key(name):
    """Sort gene.N allele names numerically on the N part."""
    parts = name.rsplit(".", 1)
    try:
        return (parts[0], int(parts[1]))
    except (IndexError, ValueError):
        return (name, 0)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args():
    parser = argparse.ArgumentParser(
        prog="mlstdb_to_ariba.py",
        description=(
            "Convert mlstdb update output to ariba pubmlstget-compatible format.\n\n"
            "Produces pubmlst_download/, clusters.tsv, and (optionally) ref_db/ "
            "that can be used directly with 'ariba run'."
        ),
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
examples:
  # minimal — auto-detects scheme, runs ariba prepareref
  python mlstdb_to_ariba.py -i mlstdb_saureus -o s_aureus_ariba

  # specify scheme explicitly  
  python mlstdb_to_ariba.py -i mlstdb_saureus -s saureus -o s_aureus_ariba

  # skip ariba prepareref (only converts files)
  python mlstdb_to_ariba.py -i mlstdb_saureus -o s_aureus_ariba --no-prepareref

  # use a specific ariba binary
  python mlstdb_to_ariba.py -i mlstdb_saureus -o s_aureus_ariba --ariba /path/to/ariba
        """,
    )
    parser.add_argument(
        "-i", "--input",
        required=True,
        metavar="DIR",
        help="mlstdb output directory (contains pubmlst/<scheme>/).",
    )
    parser.add_argument(
        "-o", "--output",
        required=True,
        metavar="DIR",
        help="Output directory to create (must not exist).",
    )
    parser.add_argument(
        "-s", "--scheme",
        default=None,
        metavar="NAME",
        help=(
            "Scheme subdirectory name inside pubmlst/ (e.g. 'saureus')."
            "Auto-detected if only one scheme is present."
        ),
    )
    parser.add_argument(
        "--ariba",
        default="ariba",
        metavar="PATH",
        help="Path to the ariba executable (default: 'ariba' on PATH).",
    )
    parser.add_argument(
        "--no-prepareref",
        action="store_true",
        help=(
            "Skip running 'ariba prepareref'. Only convert files and write"
            "clusters.tsv / pubmlst_download/. Useful if you want to inspect"
            "the output before building the database."
        ),
    )
    return parser.parse_args()


def main():
    _setup_logging()
    args = parse_args()

    try:
        out = convert(
            mlstdb_dir=args.input,
            outdir=args.output,
            scheme=args.scheme,
            ariba_bin=args.ariba,
            run_prepareref=not args.no_prepareref,
        )
        log.info("Output written to: %s", out)
    except (FileNotFoundError, FileExistsError, ValueError, RuntimeError) as exc:
        log.error("%s", exc)
        sys.exit(1)


if __name__ == "__main__":
    main()
